version: "3"
services:

  app:
    container_name: drawguessgame_backend
    restart: always
    build: .
    ports:
      - "8080:8000"
    networks:
      - app-network
    links:
      - mongo  
    depends_on:
      - mongo
    volumes:
      - "./src:/usr/src/app"  

  mongo:
    container_name: drawguessgame_db
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge