FROM node:10

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY src/package*.json ./

COPY src .

RUN npm install -g nodemon

RUN npm install

EXPOSE 8000

CMD ["nodemon", "/usr/src/app/index.js"]